name: Pieter
favicon: null
layout_spectrum: 0.2647735932841897
typography_spectrum: 0.9372839224524796
title: Ford Bronco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.07109602284617722
  lightness: 0.023161711869761348
  saturation: 0.37049269094131887
  rhythmicContrast: 0.8220429099164903
purpose: []
